IF EXISTS(SELECT 1 FROM sys.objects WHERE name='VsCHDBFStructure' AND type='U')
  DROP TABLE VsCHDBFStructure

CREATE TABLE VsCHDBFStructure 
(
	DBFName VARCHAR(50),      ---------导出DBF字段
	DBFMC   VARCHAR(100),     ---------DBF字段描述
	FieldName VARCHAR(50),    ---------来源字段
	FieldTable VARCHAR(50),   ---------来源表
	FieldSTName VARCHAR(50),  ---------关联字段
	FieldSTTable VARCHAR(50),   ----------关联表
	FieldTJ      VARCHAR(200),  ----------字段条件
	FieldCus    VARCHAR(200),   -----------自定义字段转换
	PYM VARCHAR(50),			----------拼音码
	WBM VARCHAR(50)				----------五笔码
) 

INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('USERNAME','机构名称','VsSiName','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YLFKFS','医疗付款方式','CH0A82','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('JKKH','健康卡号','CH0A81','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYCS','住院次数','','CONVERT(INT,Right(CH0A01,2))',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BAH','病案号','CH0A01','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('XM','姓名','CH0A02','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('XB','性别','CH0A03','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('CSRQ','出生日期','','Convert(VarChar(8),replace(Convert(varchar(10), CH0A04, 120),'-',''))',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('NL','年龄','CH0A06','(Case When IsNull(CH0AA1,'')<>'Y' Then 1 Else CH0A06 End)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('GJ','国籍','StdDm','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BZYZS_NL','（年龄不足1周岁的）年龄(月)','CH0A06','(CASE WHEN CH0AA1 ='M' THEN CH0A06 ELSE 0 END)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('XSETZ','新生儿出生体重(克)','','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('XSERYTZ','新生儿入院体重（克）','','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('CSD','出生地','DmMc','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('GG','籍贯','DmMc','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZ','民族','CH0A10','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SFZH','身份证号','CH0A05','Upper(CH0A05)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZY','职业','CH0A08','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('HY','婚姻','CH0A07','(Case When IsNull(CH0A07,'')='' Then '90' Else Convert(varchar(1), CH0A07)+'0' End)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('XZZ','现住址','DmMc','Convert(VarChar(100),X3.DmMc+CH0AN6)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('DH','电话','CH0AN7','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YB1','邮编','CH0AN8','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('HKDZ','户口地址','DmMc','Convert(VarChar(100),X4.DmMc+CH0A13)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YB2','邮编','CH0A14','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('GZDWJDZ','工作单位及地址','CH0AA3','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('DWDH','单位电话','CH0AA5','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YB3','邮编','CH0AA4','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('LXRXM','联系人姓名','CH0A15','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('GX','关系','CH0A16','(Case When CH0A16=9 Then 8 Else CH0A16 End)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('DZ','地址','DmMc','X5.DmMc+CH0A18',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('DH1','电话','CH0A19','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYTJ','入院途径','CH0A56','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZLLB','治疗类别','CH0A55','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYSJ','入院时间','CH0A24','Convert(VarChar(8),replace(Convert(varchar(10), CH0A24, 120),'-',''))',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYSJ_S','时','CH0A24_SJ','Left(CH0A24_SJ,charIndex(':',CH0A24_SJ)-1)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYKB','入院科别','SoKm','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYBF','入院病房','CH0ANA','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZKKB','转科科别','SoKm','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('CYSJ','出院时间','CH0A27','Convert(VarChar(8),replace(Convert(varchar(10), CH0A27, 120),'-',''))',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('CYSJ_S','时','CH0A27_SJ','Left(CH0A27_SJ,charIndex(':',CH0A27_SJ)-1)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('CYKB','出院科别','SoKm','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('CYBF','出院病房','CH0ANB','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SJZY','实际住院(天)','CH0A29','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZD_ZYZD','门(急)诊诊断(中医诊断)','BzMC','TCD1.BzMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('JBDM','疾病代码','CH0K02','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZZD_XYZD','门(急)诊诊断(西医诊断)','BmMc','ZD1.BmMc',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('JBBM','疾病编码','CH0A36','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSLCLJ','实施临床路径','Ch0ANQ','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYYJ','使用医疗机构中药制剂','CH0A70','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZLSB','使用中医诊疗设备','Ch0ANR','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZLJS','使用中医诊疗技术','Ch0ANS','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BZSH','辩证施护','Ch0ANT','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZB','主病出院中医诊断','BzMC','TCD2.BzMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZB_JBBM','主病疾病编码','CH0K06','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZB_RYBQ','主病入院病情','CH0KN1','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZD','主要诊断出院西医诊断','BmMc','ZD2.BmMc',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZD_JBBM','主要诊断疾病编码','BmICD','ZD2.BmICD',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('XY_RYBQ','主要诊断入院病情','CH0ANO','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ1','主证1出院中医诊断','BzMC','TCD3.BzMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_JBBM1','主证1疾病编码','CH0K03','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_RYBQ1','主证1住入院病情','CH0KN1','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QTZD1','其他诊断1出院西医诊断','BmMc','ZD3.BmMc',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZD_JBBM1','其他诊断1疾病编码','BmICD','ZD3.BmICD',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYBQ1','其他诊断1入院病情','CH0CN1','C1.CH0CN1',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ2','主证2出院中医诊断','BzMC','TCD3.BzMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_JBBM2','主证2疾病编码','CH0K03','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_RYBQ2','主证2入院病情','CH0KN2','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QTZD2','其他诊断2出院西医诊断','BmMc','ZD4.BmMc',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZD_JBBM2','其他诊断2疾病编码','BmICD','ZD4.BmICD',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYBQ2','其他诊断2入院病情','CH0CN1','C2.CH0CN1',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ3','主证3出院中医诊断','BzMC','TCD4.BzMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_JBBM3','主证3疾病编码','CH0K04','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_RYBQ3','主证3入院病情','CH0KN2','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QTZD3','其他诊断3出院西医诊断','BmMc','ZD5.BmMc',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZD_JBBM3','其他诊断3疾病编码','BmICD','ZD5.BmICD',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYBQ3','其他诊断3入院病情','CH0CN1','C3.CH0CN1',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ4','主证4中医诊断','BzMC','TCD5.BzMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_JBBM4','主证4疾病编码','CH0K05','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_RYBQ4','主证4入院病情','CH0KN3','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QTZD4','其他诊断4出院西医诊断','BmMc','ZD6.BmMc',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZD_JBBM4','其他诊断4疾病编码','BmICD','ZD6.BmICD',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYBQ4','其他诊断4入院病情','CH0CN1','C4.CH0CN1',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ5','主证5中医诊断','BzMC','TCD6.BzMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_JBBM5','主证5疾病编码','CH0K07','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_RYBQ5','主证入院病情','CH0KN3','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QTZD5','其他诊断5出院西医诊断','BmMc','ZD7.BmMc',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZD_JBBM5','其他诊断5疾病编码','BmICD','ZD7.BmICD',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYBQ5','其他诊断5入院病情','CH0CN1','C5.CH0CN1',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ6','主证6出院中医诊断','BzMC','TCD7.BzMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_JBBM6','主证6疾病编码','CH0K14','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_RYBQ6','主证6入院病情','CH0KN4','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QTZD6','其他诊断6西医诊断','BmMc','ZD8.BmMc',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZD_JBBM6','其他诊断6疾病编码','BmICD','ZD8.BmICD',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYBQ6','其他诊断6入院病情','CH0CN1','C6.CH0CN1',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ7','主证7出院中医诊断','BzMC','TCD8.BzMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_JBBM7','主证7疾病编码','CH0K15','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZ_RYBQ7','主证7入院病情','CH0KN4','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QTZD7','其他诊断7出院西医诊断','BmMc','ZD9.BmMc',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZD_JBBM7','其他诊断7疾病编码','BmICD','ZD9.BmICD',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYBQ7','其他诊断7入院病情','CH0CN1','C7.CH0CN1',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('WBYY','中毒的外部原因','WYMC','SS.WYMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('JBBM1','疾病编码','CH0A79','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BLZD','病理诊断','CH0D03','Left(CH0D03,100)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('JBBM2','疾病编码','CH0D07','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BLH','病理号','CH0D02','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YWGM','药物过敏','CH0A52','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('GMYW','过敏药物','DmMc','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SJ','死亡患者尸检','CH0ANC','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('XX','血型','CH0A45','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RH','Rh','CH0AC5','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('KZR','科主任','CH0AB1','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZRYS','主任（副主任）医师','CH0A32','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZYS','主治医师','CH0A33','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYYS','住院医师','CH0A34','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZRHS','责任护士','CH0AND','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('JXYS','进修医师','CH0AB2','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SXYS','实习医师','CH0AB4','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BMY','编码员','CH0A59','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BAZL','病案质量','CH0A51','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZKYS','质控医师','CH0AB5','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZKHS','质控护士','CH0A69','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZKRQ','质控日期','CH0AB6','Convert(VarChar(8),replace(Convert(varchar(10), CH0AB6, 120),'-',''))',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZBM1','手术及操作编码','SSICCM','CM1.SSICCM',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZRQ1','手术及操作日期','CH0E11','E1.CH0E11',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SHJB1','手术级别','CH0E04','E1.CH0E04',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZMC1','手术及操作名称','SSMC','CM1.SSMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SZ1','术者','CH0E09','E1.CH0E09',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YZ1','I助','CH0E14','E1.CH0E14',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('EZ1','手术及操作医师','CH0E15','E1.CH0E15',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKDJ1','手术信息切口等级','CH0E12',' (Case When IsNull(E1.CH0E01,'')='' Then Null Else (Case When E1.CH0E12=1 Then 2 When E1.CH0E12=2 Then 3 When E1.CH0E12=3 Then 4 Else 1 End) End)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKYLB1','切口愈合类别','CH0E13','(Case When IsNull(E1.CH0E01,'')='' Then Null Else (Case When (IsNull(E1.CH0E13,9)=9)or(IsNull(E1.CH0E13,0)=0) Then 9 Else E1.CH0E13 End) End) ',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZFS1','麻醉方式','WTMZM',' NA1.WTMZM',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZYS1','麻醉医师','CH0E16',' E1.CH0E16',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZBM2','手术及操作编码','SSICCM','CM2.SSICCM'
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZRQ2','手术及操作日期','CH0E11','E2.CH0E11',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SHJB2','手术信息手术级别','CH0E04','E2.CH0E04',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZMC2','手术及操作名称','SSMC','CM2.SSMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SZ2','术者','CH0E09','E2.CH0E09',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YZ2','I助','CH0E14','E2.CH0E14',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('EZ2','II助','CH0E15','E2.CH0E15',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKDJ2','切口等级','CH0E12',' (Case When IsNull(E2.CH0E01,'')='' Then Null Else (Case When E2.CH0E12=1 Then 2 When E2.CH0E12=2 Then 3 When E2.CH0E12=3 Then 4 Else 1 End) End)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKYLB2','切口愈合类别','CH0E13','(Case When IsNull(E2.CH0E01,'')='' Then Null Else (Case When (IsNull(E2.CH0E13,9)=9)or(IsNull(E2.CH0E13,0)=0) Then 9 Else E2.CH0E13 End) End) ',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZFS2','麻醉方式','WTMZM',' NA2.WTMZM',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZYS2','麻醉医师','CH0E16',' E2.CH0E16',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZBM3','手术及操作编码','SSICCM','CM3.SSICCM'
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZRQ3','手术及操作日期','CH0E11','E3.CH0E11',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SHJB3','手术级别','CH0E04','E3.CH0E04',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZMC3','手术及操作名称','SSMC','CM3.SSMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SZ3','术者','CH0E09','E3.CH0E09',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YZ3','I助','CH0E14','E3.CH0E14',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('EZ3','II助','CH0E15','E3.CH0E15',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKDJ3','切口等级','CH0E12',' (Case When IsNull(E3.CH0E01,'')='' Then Null Else (Case When E3.CH0E12=1 Then 2 When E3.CH0E12=2 Then 3 When E3.CH0E12=3 Then 4 Else 1 End) End)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKYLB3','切口愈合类别','CH0E13','(Case When IsNull(E3.CH0E01,'')='' Then Null Else (Case When (IsNull(E3.CH0E13,9)=9)or(IsNull(E3.CH0E13,0)=0) Then 9 Else E3.CH0E13 End) End) ',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZFS3','麻醉方式','WTMZM',' NA3.WTMZM',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZYS3','麻醉医师','CH0E16',' E3.CH0E16',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZBM4','手术及操作编码','SSICCM','CM4.SSICCM'
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZRQ4','手术及操作日期','CH0E11','E4.CH0E11',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SHJB4','手术级别','CH0E04','E4.CH0E04',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZMC4','手术及操作名称','SSMC','CM4.SSMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SZ4','术者','CH0E09','E4.CH0E09',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YZ4','I助','CH0E14','E4.CH0E14',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('EZ4','II助','CH0E15','E4.CH0E15',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKDJ','切口等级','CH0E12',' (Case When IsNull(E4.CH0E01,'')='' Then Null Else (Case When E4.CH0E12=1 Then 2 When E4.CH0E12=2 Then 3 When E4.CH0E12=3 Then 4 Else 1 End) End)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKYLB4','切口愈合类别','CH0E13','(Case When IsNull(E4.CH0E01,'')='' Then Null Else (Case When (IsNull(E4.CH0E13,9)=9)or(IsNull(E4.CH0E13,0)=0) Then 9 Else E4.CH0E13 End) End) ',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZFS4','麻醉方式','WTMZM',' NA4.WTMZM',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZYS4','麻醉医师','CH0E16',' E4.CH0E16',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZBM5','手术及操作编码','SSICCM','CM5.SSICCM'
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZRQ5','手术及操作日期','CH0E11','E5.CH0E11',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SHJB5','手术级别','CH0E04','E5.CH0E04',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZMC5','手术及操作名称','SSMC','CM5.SSMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SZ5','术者','CH0E09','E5.CH0E09',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YZ5','I助','CH0E14','E5.CH0E14',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('EZ5','II助','CH0E15','E5.CH0E15',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKDJ5','切口等级','CH0E12',' (Case When IsNull(E5.CH0E01,'')='' Then Null Else (Case When E5.CH0E12=1 Then 2 When E5.CH0E12=2 Then 3 When E5.CH0E12=3 Then 4 Else 1 End) End)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKYLB5','切口愈合类别','CH0E13','(Case When IsNull(E5.CH0E01,'')='' Then Null Else (Case When (IsNull(E5.CH0E13,9)=9)or(IsNull(E5.CH0E13,0)=0) Then 9 Else E5.CH0E13 End) End) ',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZFS5','麻醉方式','WTMZM',' NA5.WTMZM',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZYS5','麻醉医师','CH0E16',' E5.CH0E16',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZBM6','手术及操作编码','SSICCM','CM6.SSICCM'
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZRQ6','手术及操作日期','CH0E11','E6.CH0E11',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SHJB6','手术级别','CH0E04','E6.CH0E04',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSJCZMC6','手术及操作名称','SSMC','CM6.SSMC',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SZ6','术者','CH0E09','E6.CH0E09',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YZ6','I助','CH0E14','E6.CH0E14',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('EZ6','II助','CH0E15','E6.CH0E15',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKDJ6','切1口等级','CH0E12',' (Case When IsNull(E6.CH0E01,'')='' Then Null Else (Case When E6.CH0E12=1 Then 2 When E6.CH0E12=2 Then 3 When E6.CH0E12=3 Then 4 Else 1 End) End)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QKYLB6','切口愈合类别','CH0E13','(Case When IsNull(E6.CH0E01,'')='' Then Null Else (Case When (IsNull(E6.CH0E13,9)=9)or(IsNull(E6.CH0E13,0)=0) Then 9 Else E6.CH0E13 End) End) ',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZFS6','麻醉方式','WTMZM',' NA3.WTMZM',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZYS6','麻醉医师','CH0E16',' E6.CH0E16',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YZZY_JGMC','医嘱转院，拟接收医疗机构名称','Ch0ANF','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('WSY_JGMC','医嘱转社区卫生服务机构/乡镇卫生院，拟接收医疗机构名称','Ch0ANF','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZZYJH','是否有出院31天内再住院计划','Ch0ANG','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MD','目的','CH0ANH','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYQ_T','颅脑损伤患者昏迷入院前时间：天','Ch0ANI','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYQ_XS','颅脑损伤患者昏迷入院前时间：小时','Ch0ANJ','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYQ_FZ','颅脑损伤患者昏迷入院前时间：分钟','Ch0ANK','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYH_T','颅脑损伤患者昏迷入院后时间：天','Ch0ANL','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYH_XS','颅脑损伤患者昏迷入院后时间：小时','Ch0ANM','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('RYH_FZ','颅脑损伤患者昏迷入院后时间：分钟','Ch0ANN','',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZFY','总费用','CH0B83','ISNULL(CH0B83,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZFJE','自付金额','CH0BP1','IsNull(CH0BP1,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YLFWF','综合医疗服务类(1)一般医疗服务费','CH0BP2','IsNull(CH0BP2,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BZLZF','中医辨证论治费','Ch0BZ1','ISNULL(Ch0BZ1,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYBLZHZF','中医辨证论治会诊费','Ch0BZ2','ISNULL(Ch0BZ2,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZLCZF','一般治疗操作费','CH0BP3','ISNULL(CH0BP3,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('HLF','护理费','CH0BP4','ISNULL(CH0BP4,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QTFY','其他费用','CH0BP5','ISNULL(CH0BP5,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BLZDF','诊断类(5)病理诊断费','CH0BP6','ISNULL(CH0BP6,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZDF','实验室诊断费','CH0BP7','ISNULL(CH0BP7,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YXXZDF','影像学诊断费','CH0BP8','ISNULL(CH0BP8,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('LCZDXMF','临床诊断项目费','CH0BP9','ISNULL(CH0BP9,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('FSSZLXMF','治疗类(9)非手术治疗项目费','CH0BPA','ISNULL(CH0BPA,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZLF','临床物理治疗费','CH0BPB','ISNULL(CH0BPB,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSZLF','手术治疗费','CH0BPC','ISNULL(CH0BPC,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('MZF','麻醉费','CH0BPD','ISNULL(CH0BPD,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSF','手术费','CH0BPE','ISNULL(CH0BPE,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('KFF','康复类(11)康复费','CH0BPF','ISNULL(CH0BPF,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYL_ZYZD','中医类(中医和名族医医疗服务)（12）中医诊断','Ch0BZ3','ISNULL(Ch0BZ3,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZL','中医治疗','CH0BPG','ISNULL(CH0BPG,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYWZ','中医外治','Ch0BZ4','ISNULL(Ch0BZ4,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYGS','中医骨伤','Ch0BZ5','ISNULL(Ch0BZ5,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZCYJF','针刺与灸法','Ch0BZ6','ISNULL(Ch0BZ6,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYTNZL','中医推拿治疗','Ch0BZ7','ISNULL(Ch0BZ7,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYGCZL','中医肛肠治疗','Ch0BZ8','ISNULL(Ch0BZ8,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYTSZL','中医特殊治疗','Ch0BZ9','ISNULL(Ch0BZ9,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYQT','中医其他','Ch0BZA','ISNULL(Ch0BZA,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYTSTPJG','中医特殊调配加工','Ch0BZB','ISNULL(Ch0BZB,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BZSS','辨证施膳','Ch0BZC','ISNULL(Ch0BZC,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('XYF','西药类(15)西药费','CH0BPH','ISNULL(CH0BPH,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('KJYWF','抗菌药物费','CH0BPI','ISNULL(CH0BPI,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZCYF','中药类(16)中成药费','CH0BPJ','ISNULL(CH0BPJ,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZYZJF','医疗机构中药制剂费','Ch0BZD','ISNULL(Ch0BZD,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('ZCYF1','中草药费','CH0BPK','ISNULL(CH0BPK,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('XF','血液和血液制品类(18)血费','CH0BPL','ISNULL(CH0BPL,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('BDBLZPF','白蛋白类制品费','CH0BPM','ISNULL(CH0BPM,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QDBLZPF','球蛋白类制品费','CH0BPN','ISNULL(CH0BPN,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('NXYZLZPF','凝血因子类制品费','CH0BPO','ISNULL(CH0BPO,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('XBYZLZPF','细胞因子类制品费','CH0BPP','ISNULL(CH0BPP,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('JCYYCLF','耗材类(23)检查用一次性医用材料费','CH0BPQ','ISNULL(CH0BPQ,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('YYCLF','治疗用一次性医用材料费','CH0BPR','ISNULL(CH0BPR,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('SSYCXCLF','手术用一次性医用材料费','CH0BPS','ISNULL(CH0BPS,0)',
INSERT INTO VsCHDBFStructure(DBFName,DBFMC,FieldName,FieldCus,FieldTable,FieldSTName,FieldSTTable,FieldTJ,PYM,WBM) VALUES('QTF','其他类(26)其他费','CH0BPT','ISNULL(CH0BPT,0)',