INSERT INTO dbo.VsCH0C
        ( CHYear ,
          CH0C01 ,
          CH0C02 ,
          CH0C03 ,
          CH0C05 ,
          CH0C11 
        )
SELECT *  from  ( 
   SELECT 
YEAR(b.OUT_DAY_DATE) CHYear,
a.PATIENT_NO,
a.DIAG_ORDER,
a.SUB_ICD CH0C03,
CASE WHEN a.SUB_STATUS=5 THEN 9 ELSE a.SUB_STATUS END CH0C05,
a.SUB_ICD
 FROM KingHis.dbo.CH_SUB_DIAGNOSIS a 
 LEFT JOIN KingHis.dbo.[CH_CASE_HISTORY] b ON a.PATIENT_NO=b.PATIENT_NO 
WHERE YEAR(b.OUT_DAY_DATE)='2014' OR YEAR(b.OUT_DAY_DATE)='2015' 
        ) c WHERE NOT  EXISTS (SELECT 1 FROM dbo.VsCH0C WHERE ch0c01=c.PATIENT_NO AND CHYear=c.CHYear AND CH0C02=c.DIAG_ORDER)